package com.sizheng.afl.pojo.entity;

// Generated 2014-4-28 17:49:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusinessConsumerRecord generated by hbm2java
 */
@Entity
@Table(name = "business_consumer_record", catalog = "afl")
public class BusinessConsumerRecord implements java.io.Serializable {

	private Long id;
	private String businessId;
	private String consumerId;
	private Date consumeTime;
	private Long sceneId;
	private String consumeCode;
	private Short status;
	private Short isDelete;

	public BusinessConsumerRecord() {
	}

	public BusinessConsumerRecord(String businessId, String consumerId, Date consumeTime, Long sceneId,
			String consumeCode, Short status, Short isDelete) {
		this.businessId = businessId;
		this.consumerId = consumerId;
		this.consumeTime = consumeTime;
		this.sceneId = sceneId;
		this.consumeCode = consumeCode;
		this.status = status;
		this.isDelete = isDelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "business_id")
	public String getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	@Column(name = "consumer_id")
	public String getConsumerId() {
		return this.consumerId;
	}

	public void setConsumerId(String consumerId) {
		this.consumerId = consumerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "consume_time", length = 19)
	public Date getConsumeTime() {
		return this.consumeTime;
	}

	public void setConsumeTime(Date consumeTime) {
		this.consumeTime = consumeTime;
	}

	@Column(name = "scene_id")
	public Long getSceneId() {
		return this.sceneId;
	}

	public void setSceneId(Long sceneId) {
		this.sceneId = sceneId;
	}

	@Column(name = "consume_code", length = 500)
	public String getConsumeCode() {
		return this.consumeCode;
	}

	public void setConsumeCode(String consumeCode) {
		this.consumeCode = consumeCode;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Column(name = "is_delete")
	public Short getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Short isDelete) {
		this.isDelete = isDelete;
	}

}
