package com.sizheng.afl.pojo.entity;

// Generated 2014-4-26 23:24:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MenuBill generated by hbm2java
 */
@Entity
@Table(name = "menu_bill", catalog = "afl")
public class MenuBill implements java.io.Serializable {

	private Long id;
	private Long menuId;
	private String consumerId;
	private String consumeCode;
	private Date dateTime;
	private Short status;
	private Long sceneId;
	private Long copies;
	private String accepterId;
	private String memo;

	public MenuBill() {
	}

	public MenuBill(Long menuId, String consumerId, String consumeCode, Date dateTime, Short status, Long sceneId,
			Long copies, String accepterId, String memo) {
		this.menuId = menuId;
		this.consumerId = consumerId;
		this.consumeCode = consumeCode;
		this.dateTime = dateTime;
		this.status = status;
		this.sceneId = sceneId;
		this.copies = copies;
		this.accepterId = accepterId;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "menu_id")
	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	@Column(name = "consumer_id")
	public String getConsumerId() {
		return this.consumerId;
	}

	public void setConsumerId(String consumerId) {
		this.consumerId = consumerId;
	}

	@Column(name = "consume_code", length = 500)
	public String getConsumeCode() {
		return this.consumeCode;
	}

	public void setConsumeCode(String consumeCode) {
		this.consumeCode = consumeCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Column(name = "scene_id")
	public Long getSceneId() {
		return this.sceneId;
	}

	public void setSceneId(Long sceneId) {
		this.sceneId = sceneId;
	}

	@Column(name = "copies")
	public Long getCopies() {
		return this.copies;
	}

	public void setCopies(Long copies) {
		this.copies = copies;
	}

	@Column(name = "accepter_id")
	public String getAccepterId() {
		return this.accepterId;
	}

	public void setAccepterId(String accepterId) {
		this.accepterId = accepterId;
	}

	@Column(name = "memo", length = 500)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
