package com.sizheng.afl.pojo.entity;

// Generated 2014-3-25 17:53:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Qrcode generated by hbm2java
 */
@Entity
@Table(name = "qrcode", catalog = "afl")
public class Qrcode implements java.io.Serializable {

	private Long id;
	private String openId;
	private Long sceneId;
	private Long useLimit;
	private Long useTimes;

	public Qrcode() {
	}

	public Qrcode(String openId, Long sceneId, Long useLimit, Long useTimes) {
		this.openId = openId;
		this.sceneId = sceneId;
		this.useLimit = useLimit;
		this.useTimes = useTimes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "open_id")
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Column(name = "scene_id")
	public Long getSceneId() {
		return this.sceneId;
	}

	public void setSceneId(Long sceneId) {
		this.sceneId = sceneId;
	}

	@Column(name = "use_limit")
	public Long getUseLimit() {
		return this.useLimit;
	}

	public void setUseLimit(Long useLimit) {
		this.useLimit = useLimit;
	}

	@Column(name = "use_times")
	public Long getUseTimes() {
		return this.useTimes;
	}

	public void setUseTimes(Long useTimes) {
		this.useTimes = useTimes;
	}

}
