package com.sizheng.afl.pojo.entity;

// Generated 2014-4-26 23:24:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "afl")
public class User implements java.io.Serializable {

	private Long id;
	private String userName;
	private Long createTime;
	private Short isDeleted;
	private Integer times;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private BigDecimal precision;
	private String consumeCode;

	public User() {
	}

	public User(Integer times) {
		this.times = times;
	}

	public User(String userName, Long createTime, Short isDeleted, Integer times, BigDecimal latitude,
			BigDecimal longitude, BigDecimal precision, String consumeCode) {
		this.userName = userName;
		this.createTime = createTime;
		this.isDeleted = isDeleted;
		this.times = times;
		this.latitude = latitude;
		this.longitude = longitude;
		this.precision = precision;
		this.consumeCode = consumeCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "is_deleted")
	public Short getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Short isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "times", nullable = false)
	public Integer getTimes() {
		return this.times;
	}

	public void setTimes(Integer times) {
		this.times = times;
	}

	@Column(name = "latitude", precision = 10, scale = 6)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 10, scale = 6)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "precision_", precision = 10, scale = 6)
	public BigDecimal getPrecision() {
		return this.precision;
	}

	public void setPrecision(BigDecimal precision) {
		this.precision = precision;
	}

	@Column(name = "consume_code", length = 500)
	public String getConsumeCode() {
		return this.consumeCode;
	}

	public void setConsumeCode(String consumeCode) {
		this.consumeCode = consumeCode;
	}

}
